### ISSUE TITLE
Hi Yilun Guan

### ISSUE THREAD

**Issue by randomwangran** [guanyilun/my-emacs-config#1]
I found the map you create is cool: https://github.com/guanyilun/wuhan_viz

I also find that you are a emacs user, and possible  a user who visit emacs-china.org.

I think you are an expert in 观测宇宙学.

[I would like introduce you to the Emacs family.](https://emacs-china.org/t/topic/3374/7?u=emacs_ran)

Are you okay with it?

Ps, your profile, [Hubble Deep Field](https://zh.wikipedia.org/wiki/%E5%93%88%E5%8B%83%E6%B7%B1%E7%A9%BA) is cool

**Comment by guanyilun** [comment]
Thank you! Yes of course.
